### PR TITLE
Added POST method

### PR DESCRIPTION
**Pull request by IrynaSpyrydonova**
Closes gh-3

### CODE REVIEW

**Comment by IrynaSpyrydonova** [comment]
Hey guys, please check my post method, locally it works (hope not only for me 😂).
One thing that i would like to mention, that currently we have joi (17.2.1), not that Mosh used and  new version has a bit different validation of the scheme, so I changed it a bit. (founds the solution [here](https://github.com/sideway/joi/issues/2145))
Thank you for your time.

**Comment by yaredyilma** [comment]
Looks neatly done to me! Great job @IrynaSpyrydonova ! Thanks for the heads up on the 'Joi Validation' functionality difference! Cheers.

**Review by yaredyilma — APPROVED** [review]
Looks neatly done to me! Great job @IrynaSpyrydonova ! Thanks for the heads up on the 'Joi Validation' functionality difference! Cheers. Yared

**Review by fmkarakus — APPROVED** [review]
Well done!

**Pull request merged**
