### PR TITLE
get partial

### LINKED ISSUE #10: GET method
"Get Method
- [x] branch 'Get'
- [ ]  get method 
- [ ]  used `fs.readFile`

### PR DESCRIPTION
**Pull request by murvanessa**
Closes #10

### CODE REVIEW

**Comment by IrynaSpyrydonova** [comment]
hey hey @murvanessa. First of all you did a great job ))👍  but there are few things I want to mention.  in order to get some data, there is no need to check `validateCourse`, since we use it only for the post and put methods, where we required to put the name. I am not so sure, but what I found out, that for the fs.readFile we suppose to put 3 parameters :fs.readFile(path[, options], callback) and inside the callback send our parsed data, we can do it in your way, when we use fs.readFileSync(path[, options]). otherwise it doesnt work for me. Did it works good for you when you check it in postman? Thank you in advance 🙂

**Comment by razvanbrb** [comment]
So that means that we can not approve it yet?

**Comment by IrynaSpyrydonova** [comment]
@razvanbrb when you checked, did it work for you?

**Comment by IrynaSpyrydonova** [comment]
@murvanessa great 👍  well done, now everything works perfect 👌 Thank you

**Review by IrynaSpyrydonova — APPROVED** [review]

**Comment by IrynaSpyrydonova** [comment]
@razvanbrb if you ok with everything, we can merge 🙂

**Comment by razvanbrb** [comment]
@murvanessa  and @IrynaSpyrydonova  I see that it has a conflict.  Did you saw that? And how can we solve the conflict?

**Comment by IrynaSpyrydonova** [comment]
done

**Pull request merged**
